[toolchain]

[features]
resolution = true
skip-lint = false
verifiable = true

[programs.localnet]
lottery = "BAHGeGi5ZNZxULbTXyB8aNmHVNE7muCsFBjYRWisszB4"

[programs.devnet]
lottery = "BAHGeGi5ZNZxULbTXyB8aNmHVNE7muCsFBjYRWisszB4"

[programs.mainnet]
lottery = "BAHGeGi5ZNZxULbTXyB8aNmHVNE7muCsFBjYRWisszB4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "./local_wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
